org: artabr
app: diveshop-aws-project-api
service: diveshop-aws-project-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

plugins:
  - serverless-auto-swagger

custom:
  autoswagger:
    typefiles: ['./types/api-types.d.ts']

functions:
  getProductsList:
    handler: handler/getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
          responseData:
            200:
              description: 'List of products was served'
              bodyType: 'Products'
            500:
              description: 'Unexpected error happened'

  getProductsById:
    handler: handler/getProductsById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
          responseData:
            200:
              description: 'Product with given ID was found'
              bodyType: 'Product'
            404:
              description: 'Product not found'
            500:
              description: 'Unexpected error happened'

  createProduct:
    handler: handler/createProduct.createProduct
    events:
      - httpApi:
          path: /products
          method: post
          responseData:
            200:
              description: 'Product was created.'
              bodyType: 'Product'
            500:
              description: 'Unexpected error happened'

resources:
  Resources:
    diveshopProducts:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: diveshop_products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    diveshopStocks:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: diveshop_stocks
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
